name: Go package
on:
    push:
        branches:
            - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: |
          go build -v ./services/currency/...
          go build -v ./services/notifier/...
          go build -v ./services/gateway/...
      #
      - name: Test
        run: go test -v $(go list -f '{{.Dir}}/...' -m | xargs)

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          # optionally use a specific version of Go rather than the latest one
          go_version: "1.20"
          filter_mode: nofilter
          golangci_lint_flags: >
            --config=.golangci.yml 
            --timeout=1m
            currency/...
            gateway/...
            notifier/...
          fail_on_error: true
          cache: true
          workdir: ./services
          reporter: github-check

      - name: Install go arch
        run: go install -v github.com/fdaines/arch-go@latest

      - name: Run currency arch test
        working-directory: ./services/currency
        run: arch-go -v

      - name: Run notifier arch test
        working-directory: ./services/notifier
        run: arch-go -v
